services:
  backend:
    container_name: backend
    image: mavisgaram/mavis:backend
    environment:
      - TZ=Asia/Seoul
      - SPRING_PROFILES_ACTIVE=dev
      - JAVA_OPTS=-Xms64m -Xmx300m
    volumes:
      - ./logs:/logs
    ports:
      - "8080:8080"
    restart: always
    stop_grace_period: 40s

  admin:
    container_name: admin
    image: mavisgaram/mavis:admin
    environment:
      - TZ=Asia/Seoul
      - SPRING_PROFILES_ACTIVE=dev
      - JAVA_OPTS=-Xms32m -Xmx220m
    volumes:
      - ./logs:/logs
    ports:
      - "8081:8081"
    restart: always
    stop_grace_period: 40s
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /data/certbot/conf:/etc/letsencrypt
      - /data/certbot/www:/var/www/certbot
    depends_on:
      - backend
      - admin
    restart: always

  certbot:
    container_name: certbot
    image: certbot/certbot
    volumes:
      - /data/certbot/conf:/etc/letsencrypt
      - /data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do \
      certbot certonly --webroot -w /var/www/certbot --email chlrldnjs0804@gmail.com --agree-tos --no-eff-email --non-interactive -d api.garamall.com; \
      certbot certonly --webroot -w /var/www/certbot --email chlrldnjs0804@gmail.com --agree-tos --no-eff-email --non-interactive -d api.admin.garamall.com; \
      sleep 12h & wait $${!}; done;'"