services:
  backend:
    container_name: backend
    image: mavisgaram/backend
    environment:
      - TZ=Asia/Seoul
    volumes:
      - ./logs:/logs
    ports:
      - "8080:8080"

  admin:
    container_name: admin
    image: mavisgaram/admin
    environment:
      - TZ=Asia/Seoul
    volumes:
      - ./logs:/logs
    ports:
      - "8081:8081"
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
    restart: always
