services:
  backend:
    container_name: backend
    image: mavisgaram/backend
    environment:
      - TZ=Asia/Seoul
    volumes:
      - ./logs:/logs
    ports:
      - "8080:8080"

  admin:
    container_name: admin
    image: mavisgaram/admin
    environment:
      - TZ=Asia/Seoul
    volumes:
      - ./logs:/logs
    ports:
      - "8081:8081"
