server:
  port: 8081
  tomcat:
    max-swallow-size: -1
    max-http-form-post-size: -1

spring:
  application:
    name: mavis-admin
  flyway:
    enabled: false
  profiles:
    include:
      - infrastructure
      - domain
      - common
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  cloud:
    aws:
      region:
        static: ap-northeast-2

---

# dev 환경
spring:
  config:
    activate:
      on-profile: dev
    import: "aws-parameterstore:/config/mavis/"

---

# local 환경
spring:
  config:
    activate:
      on-profile: local
