server:
  port: 8081
  tomcat:
    max-swallow-size: -1
    max-http-form-post-size: -1
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s
  application:
    name: mavis-admin
  flyway:
    enabled: false
  profiles:
    include:
      - infrastructure
      - domain
      - common
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  cloud:
    aws:
      region:
        static: ap-northeast-2

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never

---

# dev 환경
spring:
  config:
    activate:
      on-profile: dev
    import: "aws-parameterstore:/config/mavis/"

---

# local 환경
spring:
  config:
    activate:
      on-profile: local
