dependencies {
    // Testcontainers
    testImplementation platform('org.testcontainers:testcontainers-bom:1.20.4')
    testImplementation 'org.testcontainers:mysql'
    testImplementation 'org.testcontainers:junit-jupiter'

    testImplementation 'org.springframework.security:spring-security-test'

    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'com.h2database:h2'
    runtimeOnly 'com.mysql:mysql-connector-j'

    implementation 'com.querydsl:querydsl-jpa:5.0.0:jakarta'
    annotationProcessor "com.querydsl:querydsl-apt:${dependencyManagement.importedProperties['querydsl.version']}:jakarta"
    annotationProcessor "jakarta.annotation:jakarta.annotation-api"
    annotationProcessor "jakarta.persistence:jakarta.persistence-api"

    implementation("org.springdoc:springdoc-openapi-starter-webmvc-ui:2.7.0");
    implementation 'org.springframework.boot:spring-boot-starter-security'


    implementation 'org.apache.poi:poi-ooxml:5.2.5'
    implementation project(':Mavis-Infrastructure')
    implementation project(':Mavis-Common')
    implementation project(':Mavis-Domain')

    implementation 'io.awspring.cloud:spring-cloud-aws-starter-parameter-store'
}